# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_documentaries:
    docker:
      # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
      - image: cimg/node:12.13.0
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build & Deploy Documentaries
          command: npm run deploy:documentaries

  build_weddings:
    docker:
      - image: cimg/node:12.13.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build & Deploy Weddings
          command: npm run deploy:weddings

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_and_deploy_workflow:
    jobs:
      - build_documentaries
      - build_weddings
  nightly:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - build_documentaries
      - build_weddings
